# ### Hyprland ###
# Apps
$terminal = kitty
$browser = zen-browser
$editor = zeditor
$fileExplorer = nautilus

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 1.5
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = true
$blurPopups = true
$blurInputMethods = true
$blurSize = 3
$blurPasses = 2
$blurXray = true
$blurvibrancy = 0.1696

# Shadow
$shadowEnabled = true
$shadowRange = 12
$shadowRenderPower = 2
$shadowColour = rgba(38, 38, 38, 150)

# Gaps
$workspaceGaps = 20
$windowGapsIn = 10
$windowGapsOut = 40
$singleWindowGapsOut = 20

# Window styling
$windowOpacity = 0.95
$windowRounding = 20

$windowBorderSize = 3
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 5  # In percent
$cursorTheme = nier-cursors-bin
$cursorSize = 24


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super, Q

# Apps
$kbTerminal = Super, T
$kbBrowser = Super, W
$kbFileExplorer = Super, E

# Misc
$kbLock = Super, L
