animations {
	enabled = true
# Bezier Curves
	bezier = ease, 0.12, 0, 0.39, 0
	bezier = easeInOutBack, 0.68, -0.6, 0.32, 1.6 
	bezier = easeOutQuint, 0.22, 1, 0.36, 1
	bezier = easeInOutQuart, 0.73, -0.21, 0.35, 1.24
	
	
# Animations
	# Window Actions
	animation = windowsIn, 1, 5, easeInOutBack, popin
	animation = windowsOut, 1, 4, ease, slide
	animation = windowsMove, 1, 5, easeInOutBack
	
	# Workspaces
	animation = workspacesIn, 1, 5, easeInOutQuart, slidefadevert
	animation = workspacesOut, 1, 5, easeInOutQuart, slidefade 50%
	
	# Special Workspaces
	animation = specialWorkspaceIn,1 ,5, easeOutQuint, slidefadevert 20%
	animation = specialWorkspaceOut,1 ,5, easeOutQuint, fade
	
	# Layers
	animation = layersIn, 1, 5, easeOutQuint, popin
	animation = layersOut, 1, 5, easeOutQuint, popin
	
	# Fades
	animation = fade, 1, 4, ease
}
