general {
    layout = scrolling

    allow_tearing = false  # Allows `immediate` window rule to work

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize
}

dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
}
scrolling{
follow_focus = true
follow_min_visible = 0.1
}
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
