input {

    kb_layout = us
    numlock_by_default = true
    repeat_delay = 500
    repeat_rate = 35
    kb_options = caps:none

    follow_mouse = 1

    focus_on_close = 1

    touchpad {
        natural_scroll = true
        middle_button_emulation=true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}
device {
    name = logitech-wireless-mouse-1
    natural_scroll = true
    middle_button_emulation=true
    sensitivity = 0.0
    scroll_method= on_button_down
    scroll_button = 274

}
binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}
